image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  SERVER_USERNAME: "2dt46WeD"
  SERVER_PASSWORD: "BS4rJ8aQVdVaeL/EV3DURmhvIFGh5DGzxxD9L5w3CcvL"
cache:
  paths:
    - target/
    - .m2/repository/
build:
  stage: build
  script:
    - mvn $MAVEN_OPTS clean package
deploy:
  stage: deploy
  script:
    - git config --global user.email "ptdien.lxag@gmail.com"
    - git config --global user.name "Dien Phan Thanh"
    - mvn $MAVEN_OPTS -Dserver.username=$SERVER_USERNAME -Dserver.password=$SERVER_PASSWORD release:clean release:prepare release:perform
